import { MealCandidate } from '@/types/meal';

export const FALLBACK_MEALS: MealCandidate[] = [
  {
    id: 'fallback_1',
    name: '白米と味噌汁',
    category: 'rice_set',
    form: 'cook',
    time_min: 10,
    cost_band: 'low',
    nutrition_tags: ['炭水化物', '発酵食品'],
    reason: 'シンプルで安心できる定番の食事です',
    ingredients: ['白米', '味噌', '豆腐', 'ネギ', 'わかめ'],
    steps: ['ご飯を炊く', '出汁を取る', '具材を加えて味噌を溶かす'],
    shopping_list: ['味噌', '豆腐', 'わかめ'],
  },
  {
    id: 'fallback_2',
    name: 'コンビニおにぎり＋サラダ',
    category: 'convenience',
    form: 'buy',
    time_min: 10,
    cost_band: 'low',
    nutrition_tags: ['炭水化物', '野菜'],
    reason: '手軽に栄養バランスが取れる組み合わせです',
    ingredients: ['おにぎり', 'サラダ'],
    steps: ['コンビニで購入する'],
    shopping_list: ['おにぎり（好みの具）', 'カット野菜サラダ', 'ドレッシング'],
  },
  {
    id: 'fallback_3',
    name: '親子丼',
    category: 'donburi',
    form: 'cook',
    time_min: 20,
    cost_band: 'low',
    nutrition_tags: ['たんぱく質', '炭水化物'],
    reason: '短時間で作れる栄養豊富な丼ものです',
    ingredients: ['鶏もも肉', '卵', '玉ねぎ', '白米', 'だし醤油', 'みりん'],
    steps: [
      '鶏肉と玉ねぎを炒める',
      'だし醤油・みりんで煮る',
      '卵でとじてご飯にのせる',
    ],
    shopping_list: ['鶏もも肉', '卵', '玉ねぎ', 'だし醤油', 'みりん'],
  },
  {
    id: 'fallback_4',
    name: 'ざるそば',
    category: 'noodle',
    form: 'cook',
    time_min: 10,
    cost_band: 'low',
    nutrition_tags: ['炭水化物', 'さっぱり'],
    reason: 'さっぱりして食べやすい軽食です',
    ingredients: ['そば', 'めんつゆ', 'ネギ', 'わさび'],
    steps: ['そばを茹でる', '冷水でしめる', 'つゆで食べる'],
    shopping_list: ['そば', 'めんつゆ', 'ネギ', 'わさび'],
  },
  {
    id: 'fallback_5',
    name: 'トースト＋目玉焼き',
    category: 'bread',
    form: 'cook',
    time_min: 10,
    cost_band: 'low',
    nutrition_tags: ['炭水化物', 'たんぱく質'],
    reason: '朝食にも昼食にも使える手軽な一品です',
    ingredients: ['食パン', '卵', 'バター', '塩', 'コショウ'],
    steps: ['パンをトーストする', '卵を焼く', 'バターを塗って盛り付ける'],
    shopping_list: ['食パン', '卵', 'バター'],
  },
];
